spring:
  config:
    import: optional:classpath:.env[.properties]

  application:
    name: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: Asia/Seoul
        hbm2ddl:
          halt_on_error: false
    hibernate:
      ddl-auto: update
    open-in-view: true

  mail :
    host : smtp.gmail.com
    port : 587
    username :
    password :
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: sdf
            client-secret: asdsd
            authorization-grant-type: authorization_code
            scope:
              - email
              - gender
              - birthday
              - birthyear
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          google:
            client-name: google
            client-id: asdasd
            client-secret: asdad
            scope:
              - email
          kakao:
            client-name: kakao
            client-id: adsd
            client-secret: asasd
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - gender
              - birthday
              - birthyear
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

logging:
  level:
    p6spy: info


jwt:
  secret-key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: "JWT_ISSUER"
