spring:
  datasource:
    url: jdbc:h2:mem:~/playhive;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          exception-handling: ignore

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            scope:
              - email
              - gender
              - birthday
              - birthyear
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          google:
            client-name: google
            client-id:
            client-secret:
            scope:
              - email
          kakao:
            client-name: kakao
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - gender
              - birthday
              - birthyear
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

  data:
    redis:
      host: localhost
      port: 6379
      password: test

jwt:
  issuer: "JWT_ISSUER"
  secret-key: "mySuperSecretKeyForJwtAuthThatIsLongEnough1234"
