name: moiraBackEndTest

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        env:

          REDIS_ARGS: "--requirepass test"

        ports:
          - 6379:6379


        #env:
         # REDIS_PASSWORD: test
    steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK 21 
      uses: actions/setup-java@v1
      with:
        java-version: 21 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      env:
        SPRING_MONGODB_PORT: ${{ secrets.TEST_MONGO_PORT }}
        SPRING_MONGODB_URI: mongodb+srv://${{secrets.MONGO_TEST_USER_NAME}}:${{secrets.TEST_MONGO_PASSWORD}}@${{secrets.MONGO_TEST_USER_NAME}}.qayje6x.mongodb.net/?retryWrites=true&w=majority&appName=${{secrets.MONGO_TEST_USER_NAME}}"
        SPRING_MONGODB_DATABASE: ${{secrets.TEST_MONGO_DB_NAME}}
      run: ./gradlew clean test
